### ISSUE TITLE
Game is too difficult

### ISSUE THREAD

**Issue by chitsuenchan** [seewahtse/hangman#1]
Hi Mr Seewa,

I've been playing your hangman game multiple times with my friend and although we really enjoy it. We feel sometimes the words are just too tough. For example, we have words such as :
- demyelinations
- foulards
- maderizing
- agrochemical

It would be great if there was an easy mode where it has easy words as "dog" or "cat" or "mat".

**Comment by seewahtse** [comment]
Hi Mr Chi,

I've added a functionality where the user selects easy, medium or hard. A word is then chosen based on the length corresponding to the difficulty selected. Please try the game again now 

xoxo
